### ISSUE TITLE
需要點擊第2次

### ISSUE THREAD

**Issue by tenSunFree** [hanks-zyh/SmallBang#11]
先謝謝你的分享, 覺得很漂亮實用

然後我想請問一下, 我把它放到RecyclerView裡使用
但是我發覺, 點擊有些Item需要點第2次, 才會出現動畫效果

我點擊的時候, 是直接調用like_heart.likeAnimation()

想請問一下, 是什麼原因? 我忽略了那些細節?

**Comment by hanks-zyh** [comment]
@

**Comment by hanks-zyh** [comment]
你可以先看下demo里的代码，看看是否是你想要实现的效果

**Comment by tenSunFree** [comment]
我解決問題了, 謝謝~
