### ISSUE TITLE
Option to set start and end view?

### ISSUE THREAD

**Issue by broakenmedia** [hanks-zyh/SmallBang#3]
Something like the heart icon for example. Would need to start grey and become red once tapped and the animation has been finished. I presume this can be done in the onAnimationEnd but how well does that sync with the animation? I can imagine it looking like it's just popping in at the end instead of flowing nicely

**Comment by hanks-zyh** [comment]
i have been release v1.2.0 by re-implement the animation, please have a try

```
dependencies {
    implementation 'pub.hanks:smallbang-library:1.2.0'
}
```
