### ISSUE TITLE
SmallBang in custom AlertDialog

### ISSUE THREAD

**Issue by ivandiazmolina** [hanks-zyh/SmallBang#5]
Hi, I use your library in my custom Alert dialog but the effect appear in top activity (see purple circle in top)
![captura de pantalla 2016-02-12 a las 9 59 34](https://cloud.githubusercontent.com/assets/5048460/13003104/d2668c04-d173-11e5-8e74-91c2f5b28877.png)

**Comment by hanks-zyh** [comment]
@ivandiazmolina Thank you for your feedback, I am sorry that it is a bug, the animation view is an subview  of the  view (`activity.findViewById(Window.ID_ANDROID_CONTENT) ` ), Dialog is a special type of window. if you want to use it in AlertDialog, you have to modify the source code.

**Comment by cervy** [comment]
the same problem as PopupWindow

**Comment by hanks-zyh** [comment]
@ivandiazmolina @cervy  
this problem have been solved
i have been release v1.2.0 by re-implement the animation, please have a try

```
dependencies {
    implementation 'pub.hanks:smallbang-library:1.2.0'
}
```
