### ISSUE TITLE
Speed Up of Animation

### ISSUE THREAD

**Issue by GauravCreed** [hanks-zyh/SmallBang#8]
Hi @hanks-zyh 

It was great animation on widget, i want to speed up (fast) animation on click, is it possible ? then how ? in my code ...

`
imgHome.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mSmallBang.bang(view,50,new SmallBangListener() {
                @Override
                public void onAnimationStart() {    }

```
            @Override
            public void onAnimationEnd() {    }
        });
        }
    });
```

`

Thanks.

**Comment by cesarferreira** [comment]
Sorry, I'm kinda lost in here, why did you mentioned me?

**Comment by hanks-zyh** [comment]
@GauravCreed 
i have been release v1.2.0 by re-implement the animation, please have a try

```
dependencies {
    implementation 'pub.hanks:smallbang-library:1.2.0'
}
```
